global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-backend'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    static_configs:
      # Se estiver usando o IntelliJ/Eclipse localmente: host.docker.internal:8080
      # Se no Docker também, use o container_name ou o service (ex: backend:8080)
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'biblioo'