{
 "title": "Monitoramento Biblioo",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requisições por endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (uri, method, status) (rate(http_server_requests_seconds_count{application=\"biblioo\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latência por endpoint (gargalos)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum by (uri, le) (\r\n    rate(http_server_requests_seconds_bucket{application=\"biblioo\"}[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência média por endpoint (segundos)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_sum{application=\"biblioo\"}[5m])) / sum by (uri) (rate(http_server_requests_seconds_count{application=\"biblioo\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Erros 4xx e 5xx por endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (uri, status) (\r\n  rate(http_server_requests_seconds_count{application=\"biblioo\", status=~\"4..|5..\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 endpoints mais acessados",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(10, sum by (uri) (\r\n  increase(http_server_requests_seconds_count{application=\"biblioo\", uri!~\"/actuator.*|/swagger.*|/v3.*\"}[1h])\r\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoints mais lentos agora",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "topk(5,\r\n  sum by (uri) (rate(http_server_requests_seconds_sum{application=\"biblioo\", uri!~\"/actuator.*|/swagger.*|/v3.*\"}[5m]))\r\n  /\r\n  sum by (uri) (rate(http_server_requests_seconds_count{application=\"biblioo\", uri!~\"/actuator.*|/swagger.*|/v3.*\"}[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conexões ativas no banco (Hikari)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"biblioo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de erros % por endpoint",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (uri) (\r\n  rate(http_server_requests_seconds_count{application=\"biblioo\", status=~\"4..|5..\"}[5m])\r\n)\r\n/\r\nsum by (uri) (\r\n  rate(http_server_requests_seconds_count{application=\"biblioo\"}[5m])\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hit rate (Redis",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cache_gets_total{application=\"biblioo\", result=\"hit\"}[5m]))\r\n/\r\nsum(rate(cache_gets_total{application=\"biblioo\", result=~\"hit|miss\"}[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}